### ISSUE TITLE
Outdated version of QT causes segfault

### ISSUE THREAD

**Issue by JJTech0130** [JJTech0130/MultiMC5#25]
System Information
-----------------------------
MultiMC version: 0.6.11

Operating System: RPiOS (64-bit)

Summary of the issue or suggestion:
----------------------------------------------
When you close the "Edit Instance" window MultiMC crashes with error `./MultiMC: line 93: 30110 Segmentation fault "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"`

What should happen:
------------------------------
MultiMC should continue and work fine as on other architectures.

Steps to reproduce the issue (Add more if needed):
-------------------------------------------------------------
1. Launch MultiMC compiled for ARM64 (eg. https://github.com/JJTech0130/MultiMC5/releases/tag/0.6.11)

2. Add an instance.

3. Select "Edit Instance" then close the window that appears.

Suspected cause:
---------------------------
Using `clang` to compile?

Logs/Screenshots:
----------------------------
[//]: # (Please refer to https://github.com/MultiMC/MultiMC5/wiki/Log-Upload for instructions on how to attach your logs.)
```
1578.036 D Download succeeded: "https://jjtech0130.github.io/v1/org.lwjgl3/index.json"
 1578.036 D Task "NetJob(Download of meta file org.lwjgl3/index.json)" succeeded
./MultiMC: line 96: 27697 Segmentation fault      "${MMC_DIR}/bin/MultiMC" -d "${MMC_DIR}" "$@"
```

Additional Info:
---------------------------
None

**Comment by JJTech0130** [comment]
Here is the output of GDB at the time of the segfault
```
   58.124 D Task "ComponentUpdateTask(0x555633f150)" succeeded
   58.124 D Component list update/resolve task succeeded for "1.8.9"
[Thread 0x7fdccee190 (LWP 3651) exited]

Thread 1 "MultiMC" received signal SIGSEGV, Segmentation fault.
0x0000007ff7a8eadc in QWidgetPrivate::reparentFocusWidgets(QWidget*) () from /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
(gdb) bt
#0  0x0000007ff7a8eadc in QWidgetPrivate::reparentFocusWidgets(QWidget*) () from /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
#1  0x0000007ff7a94e6c in QWidget::setParent(QWidget*, QFlags<Qt::WindowType>) () from /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
#2  0x0000007ff7a96f4c in QWidgetAction::releaseWidget(QWidget*) () from /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
#3  0x0000007ff7c0f3cc in ?? () from /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
#4  0x0000007ff7c0f4e4 in ?? () from /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
#5  0x0000007ff7a8f754 in QWidget::~QWidget() () from /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
#6  0x000000555572850c in WideBar::~WideBar (this=0x555662cdd0, __in_chrg=<optimized out>) at /media/pi/DATA/MultiMC5/application/widgets/WideBar.cpp:55
#7  0x0000007ff6bab5dc in QObjectPrivate::deleteChildren() () from /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#8  0x0000007ff7a8f938 in QWidget::~QWidget() () from /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
#9  0x000000555568be1c in ScreenshotsPage::~ScreenshotsPage (this=0x5556621ff0, __in_chrg=<optimized out>) at /media/pi/DATA/MultiMC5/application/pages/instance/ScreenshotsPage.cpp:266
#10 0x0000007ff6bab5dc in QObjectPrivate::deleteChildren() () from /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#11 0x0000007ff7a8f938 in QWidget::~QWidget() () from /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
#12 0x00000055557451f4 in PageContainer::~PageContainer (this=0x7fec00e3c0, __in_chrg=<optimized out>) at /media/pi/DATA/MultiMC5/application/pages/BasePageContainer.h:6
#13 PageContainer::~PageContainer (this=0x7fec00e3c0, __in_chrg=<optimized out>) at /media/pi/DATA/MultiMC5/build/application/MultiMC_autogen/IMAN36LHMA/../../../../application/widgets/PageContainer.h:40
#14 0x0000007ff6bab5dc in QObjectPrivate::deleteChildren() () from /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#15 0x0000007ff7a8f938 in QWidget::~QWidget() () from /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
#16 0x000000555565839c in InstanceWindow::~InstanceWindow (this=0x7fec012960, __in_chrg=<optimized out>) at /media/pi/DATA/MultiMC5/application/InstanceWindow.cpp:218
#17 0x0000007ff6badef8 in QObject::event(QEvent*) () from /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#18 0x0000007ff7a93c54 in QWidget::event(QEvent*) () from /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
#19 0x0000007ff7b909e8 in QMainWindow::event(QEvent*) () from /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
#20 0x0000007ff7a543d4 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
#21 0x0000007ff7a5ba8c in QApplication::notify(QObject*, QEvent*) () from /usr/lib/aarch64-linux-gnu/libQt5Widgets.so.5
#22 0x0000007ff6b82618 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#23 0x0000007ff6b85820 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#24 0x0000007ff6bd9b50 in ?? () from /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#25 0x0000007ff5c86674 in g_main_context_dispatch () from /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
#26 0x0000007ff5c868e8 in ?? () from /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0
#27 0x0000007ff5c86984 in g_main_context_iteration () from /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0
#28 0x0000007ff6bd904c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#29 0x0000007ff39656a8 in ?? () from /usr/lib/aarch64-linux-gnu/libQt5XcbQpa.so.5
#30 0x0000007ff6b80ed8 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#31 0x0000007ff6b89734 in QCoreApplication::exec() () from /usr/lib/aarch64-linux-gnu/libQt5Core.so.5
#32 0x000000555561f35c in main (argc=<optimized out>, argv=0x7ffffff0b8) at /media/pi/DATA/MultiMC5/application/main.cpp:54
```

**Comment by JJTech0130** [comment]
Same issue as https://github.com/MultiMC/MultiMC5/issues/2797. Apparently it is a Debian 10 (Buster) thing. Guess we can’t fix it. Just use a different version of QT
